version: '2'
services:
    pgwitg-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/pgwitg/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=pgwitg
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
